### ISSUE TITLE
Consider linking to meta.pycqa.org for PyCQA.

### ISSUE THREAD

**Issue by tomprince** [pyaa/authority#4]
The only reason I didn't submit a pull-request, is because it sadly doesn't support https.

(cc: @sigmavirus24)

**Comment by sigmavirus24** [comment]
:+1: See also pycqa/meta#8

**Comment by glyph** [comment]
I think we have to consider this blocked until HTTPS is available. While our domain is authority and not authentication or authorization, all the auth's have to stick together.

**Comment by glyph** [comment]
Closing this until such time as HTTPS is available.
